
# SEO settings
title: Steve Sebastian - Vision Scientist
stylished_title: Steve Sebastian
description: "Writings on my projects."
keywords: "coding, machine learning, computer vision, neuroscience, psychology, vision, eye"
url: http://stephensebastian.com
baseurl: ""

google_analytics: 
disqus_shortname: ""

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

paginate: 3
paginate_path: "/page/:num/"
comments: true

#source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Steve Sebastian
  thumb    : https://en.gravatar.com/userimage/42626876/ff31b74f207c61cc9d2d1d9196fd0080.jpg?size=120
  email    : sebastian@utexas.edu
  url      : http://stephensebastian.com
  github   : http://github.com/stevesebastian
  linkedin : hhttps://www.linkedin.com/in/stephen-sebastian-701600a3
project:
    repo: https://github.com/codinfox/TIL
    name: TIL
    author: codinfox

gems:
  #- bourbon
  - jekyll-paginate

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
